baseURL = "https://tilburgnetworkgroup.github.io/remify/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "remify (v1.1.0)"
theme = "docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


# [Languages]
# [Languages.en]
# title = "remify (v1.1.0)"
# weight = 1
# languageName = "English"
# 
# [Languages.fr]
# title = "remify (v1.1.0)"
# weight = 2
# languageName = "Français"


[markup]
[markup.goldmark.renderer]
unsafe = true

[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = true # default is false
disableSearch = false # default is false
disableNavChevron = true # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
enableGitInfo = true


[outputs]
home = [ "HTML", "RSS", "JSON"]

[menu]
    [[menu.main]]
    name = "Installation"
    identifier = "installation"
    url = "/installation/"
    weight = 2

    [[menu.shortcuts]]
    name = "<i class='fa fa-spinner'></i> <label>remverse</label>"
    url = "https://tilburgnetworkgroup.github.io/remverse/"
    weight = 11

    [[menu.shortcuts]]
    pre = "<h3>More</h3>"
    name = "<i class='fa fa-github'></i> <label>Github</label>"
    identifier = "ds"
    url = "https://github.com/TilburgNetworkGroup/"
    weight = 20

    [[menu.shortcuts]]
    name = "<i class='fa fa-twitter'></i> <label>Twitter</label>"
    url = "https://twitter.com/tiunetworkgroup"
    weight = 31
