# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rehCpp <- function(edgelist, actors, types, directed, ordinal, origin, omit_dyad, model) {
    .Call('_remify_rehCpp', PACKAGE = 'remify', edgelist, actors, types, directed, ordinal, origin, omit_dyad, model)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_remify_RcppExport_registerCCallable', PACKAGE = 'remify')
})
